name: Verificación de código

on:
  pull_request:
    branches:
      - main

jobs:
  code_verification:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2
        
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Instalar dependencias
        run: pip install -r requirements.txt
        
      - name: Ejecutar pruebas unitarias
        run: pytest test_train.py

